[tool.pyright]
include = ["./modules"]
defineConstant = { DEBUG = true }

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonPlatform = "Linux"

executionEnvironments = [
  { root = "./" }
]
